package ar.com.intrale.strings.catalog

import ar.com.intrale.strings.model.MessageKey

internal val DefaultCatalog_es: Map<MessageKey, String> = mapOf(
    MessageKey.app_name to "Intrale",
    MessageKey.buttons_preview_login to "Iniciar sesión",
    MessageKey.buttons_preview_logout to "Cerrar sesión",
    MessageKey.buttons_preview_signup to "Crear cuenta",
    MessageKey.buttons_preview_title to "Vista previa de botones",
    MessageKey.dashboard_title to "Panel principal",
    MessageKey.dashboard_menu_hint to "Desplegá el menú para acceder a las acciones principales.",
    MessageKey.dashboard_menu_open_description to "Menú. Deslizá a la derecha para volver. Deslizá hacia abajo para abrir. Tocá para abrir o cerrar.",
    MessageKey.dashboard_menu_close_description to "Cerrar menú de acciones",
    MessageKey.dashboard_menu_long_press_hint to "Deslizá a la derecha para volver y hacia abajo para abrir",
    MessageKey.dashboard_menu_buttons_preview to "Demo de botones Intrale",
    MessageKey.dashboard_menu_change_password to "Cambiar contraseña",
    MessageKey.dashboard_menu_setup_two_factor to "Configurar autenticación en dos pasos",
    MessageKey.dashboard_menu_verify_two_factor to "Verificar autenticación en dos pasos",
    MessageKey.dashboard_menu_personalization to "Personalización",
    MessageKey.dashboard_menu_request_join_business to "Solicitar unión",
    MessageKey.dashboard_menu_review_business_requests to "Revisar solicitudes de negocio pendientes",
    MessageKey.dashboard_menu_review_join_requests to "Revisar solicitudes de unión",
    MessageKey.dashboard_menu_register_saler to "Registrar vendedor",
    MessageKey.dashboard_menu_logout to "Salir",
    MessageKey.app_back_button to "Volver",
    MessageKey.app_home_icon_content_description to "Ir al inicio",
    MessageKey.app_missing_title to "Pantalla sin título",
    MessageKey.home_title to "Inicio",
    MessageKey.home_headline to "Impulsamos tu operación con Intrale",
    MessageKey.home_subtitle to "Ingresá o registrate para centralizar tu negocio y la gestión de tu red comercial.",
    MessageKey.change_password_current_password to "Contraseña actual",
    MessageKey.change_password_submit to "Actualizar contraseña",
    MessageKey.change_password_success to "Contraseña actualizada",
    MessageKey.confirm_password_recovery to "Confirmar recuperación",
    MessageKey.email to "Correo electrónico",
    MessageKey.confirm_password_recovery_code to "Código",
    MessageKey.confirm_password_recovery_email to "Correo electrónico",
    MessageKey.confirm_password_recovery_success to "Contraseña actualizada",
    MessageKey.error_generic to "Ocurrió un error. Intentá nuevamente.",
    MessageKey.family_name to "Apellido",
    MessageKey.login_button to "Ingresar",
    MessageKey.login_change_password_description to "Tu cuenta requiere actualizar la contraseña antes de ingresar.",
    MessageKey.login_change_password_required to "Actualizá tu contraseña para continuar",
    MessageKey.login_change_password_title to "Actualizá tu contraseña",
    MessageKey.login_email_placeholder to "correo@intrale.com",
    MessageKey.login_error_credentials to "Usuario o contraseña incorrectos",
    MessageKey.login_family_name_placeholder to "Apellido",
    MessageKey.login_generic_error to "Ocurrió un error al iniciar sesión. Intentá nuevamente.",
    MessageKey.login_name_placeholder to "Nombre",
    MessageKey.login_new_password_placeholder to "Nueva contraseña segura",
    MessageKey.login_password_icon_content_description to "Ícono de contraseña",
    MessageKey.login_password_placeholder to "Tu contraseña",
    MessageKey.login_subtitle to "Ingresá con tu correo corporativo para continuar.",
    MessageKey.login_title to "Bienvenido a Intrale",
    MessageKey.login_user_icon_content_description to "Ícono de usuario",
    MessageKey.first_name to "Nombre",
    MessageKey.new_password to "Nueva contraseña",
    MessageKey.password to "Contraseña",
    MessageKey.password_recovery to "Recuperar contraseña",
    MessageKey.password_recovery_email_sent to "Correo enviado",
    MessageKey.business to "Negocio",
    MessageKey.request_join_business to "Solicitar unión",
    MessageKey.request_join_business_sent to "Solicitud enviada",
    MessageKey.register_business to "Registrar negocio",
    MessageKey.signup to "Registrarme",
    MessageKey.signup_delivery to "Registro Delivery",
    MessageKey.text_field_hide_password to "Ocultar contraseña",
    MessageKey.text_field_show_password to "Mostrar contraseña",
    MessageKey.username to "Usuario",
)
