package ar.com.intrale.strings.catalog

import ar.com.intrale.strings.model.MessageKey

internal val DefaultCatalog_es: Map<MessageKey, String> = mapOf(
    MessageKey.app_name to "Intrale",
    MessageKey.buttons_preview_login to "Iniciar sesión",
    MessageKey.buttons_preview_logout to "Cerrar sesión",
    MessageKey.buttons_preview_signup to "Crear cuenta",
    MessageKey.buttons_preview_title to "Vista previa de botones",
    MessageKey.dashboard_title to "Panel principal",
    MessageKey.dashboard_menu_hint to "Desplegá el menú para acceder a las acciones principales.",
    MessageKey.dashboard_menu_open_description to "Menú. Deslizá a la derecha para volver. Deslizá hacia abajo para abrir. Tocá para abrir o cerrar.",
    MessageKey.dashboard_menu_close_description to "Cerrar menú de acciones",
    MessageKey.dashboard_menu_long_press_hint to "Deslizá a la derecha para volver y hacia abajo para abrir",
    MessageKey.dashboard_menu_buttons_preview to "Demo de botones Intrale",
    MessageKey.dashboard_menu_title to "Mi cuenta",
    MessageKey.dashboard_menu_change_password to "Cambiar contraseña",
    MessageKey.dashboard_menu_setup_two_factor to "Configurar autenticación en dos pasos",
    MessageKey.dashboard_menu_verify_two_factor to "Verificar autenticación en dos pasos",
    MessageKey.dashboard_menu_personalization to "Personalización",
    MessageKey.personalization_title to "Personalización",
    MessageKey.personalization_access_denied to "No tenés permiso para acceder a esta sección",
    MessageKey.personalization_business_context to "Negocio actual: {businessId}",
    MessageKey.personalization_description to "Configurá la apariencia de tu negocio",
    MessageKey.personalization_section_pending to "Disponible próximamente",
    MessageKey.personalization_section_colors to "Colores",
    MessageKey.personalization_section_typography to "Tipografías",
    MessageKey.personalization_section_images to "Imágenes",
    MessageKey.personalization_section_app_icon to "Ícono de app",
    MessageKey.personalization_section_preview to "Previsualización",
    MessageKey.dashboard_menu_business_products to "Productos",
    MessageKey.business_products_title to "Productos",
    MessageKey.business_products_add_action to "Agregar producto",
    MessageKey.business_products_filter_all to "Todos",
    MessageKey.business_products_filter_published to "Publicados",
    MessageKey.business_products_filter_drafts to "Borradores",
    MessageKey.business_products_empty to "Todavía no tenés productos cargados.",
    MessageKey.business_products_error to "No pudimos cargar los productos. Reintentá más tarde.",
    MessageKey.business_products_retry to "Reintentar",
    MessageKey.business_products_status_published to "Publicado",
    MessageKey.business_products_status_draft to "Borrador",
    MessageKey.business_products_status_unknown to "Estado desconocido",
    MessageKey.business_products_access_denied to "Necesitás seleccionar un negocio y tener permisos de administrador para ver los productos.",
    MessageKey.product_list_missing_business to "Seleccioná un negocio para gestionar productos.",
    MessageKey.product_form_title_create to "Nuevo producto",
    MessageKey.product_form_title_edit to "Editar producto",
    MessageKey.product_form_name to "Nombre del producto",
    MessageKey.product_form_short_description to "Descripción corta",
    MessageKey.product_form_base_price to "Precio base",
    MessageKey.product_form_unit to "Unidad",
    MessageKey.product_form_category to "Categoría",
    MessageKey.product_form_status to "Estado",
    MessageKey.product_form_save to "Guardar",
    MessageKey.product_form_delete to "Eliminar producto",
    MessageKey.product_form_delete_confirm_title to "Eliminar producto",
    MessageKey.product_form_delete_confirm_message to "¿Seguro que querés eliminar este producto?",
    MessageKey.product_form_delete_confirm_accept to "Eliminar",
    MessageKey.product_form_delete_confirm_cancel to "Cancelar",
    MessageKey.product_form_error_invalid_price to "Ingresá un precio válido mayor a 0",
    MessageKey.product_form_missing_business to "Necesitás seleccionar un negocio para continuar.",
    MessageKey.product_form_saved to "Producto guardado",
    MessageKey.product_form_deleted to "Producto eliminado",
    MessageKey.dashboard_menu_request_join_business to "Solicitar unión",
    MessageKey.dashboard_menu_review_business_requests to "Revisar solicitudes de negocio pendientes",
    MessageKey.dashboard_menu_review_join_requests to "Revisar solicitudes de unión",
    MessageKey.dashboard_menu_register_saler to "Registrar vendedor",
    MessageKey.dashboard_menu_logout to "Salir",
    MessageKey.app_back_button to "Volver",
    MessageKey.app_home_icon_content_description to "Ir al inicio",
    MessageKey.app_missing_title to "Pantalla sin título",
    MessageKey.home_title to "Inicio",
    MessageKey.home_headline to "Impulsamos tu operación con Intrale",
    MessageKey.home_subtitle to "Ingresá o registrate para centralizar tu negocio y la gestión de tu red comercial.",
    MessageKey.business_onboarding_title to "Administrá tu negocio con Intrale",
    MessageKey.business_onboarding_subtitle to "Onboarding para administradores: configurá equipo, pedidos y tienda con foco en negocio.",
    MessageKey.business_onboarding_value_store_title to "Controlá tu tienda",
    MessageKey.business_onboarding_value_store_description to "Centralizá catálogo, aperturas y acciones clave de tus sucursales.",
    MessageKey.business_onboarding_value_team_title to "Gestioná tu equipo",
    MessageKey.business_onboarding_value_team_description to "Invitá administradores y repartidores con roles y permisos alineados a tu negocio.",
    MessageKey.business_onboarding_value_monitor_title to "Monitoreá pedidos y panel",
    MessageKey.business_onboarding_value_monitor_description to "Ingresá directo al dashboard BAPP-003 para seguir pedidos y configuraciones críticas.",
    MessageKey.delivery_home_title to "Inicio para repartidores",
    MessageKey.delivery_home_headline to "Bienvenido a tu app de repartos",
    MessageKey.delivery_home_subtitle to "Ingresá con tus credenciales o solicitá acceso para sumarte al negocio.",
    MessageKey.delivery_home_greeting to "Hola, repartidor",
    MessageKey.delivery_home_today to "Hoy es {date}",
    MessageKey.delivery_home_summary_title to "Resumen del día",
    MessageKey.delivery_home_active_title to "Pedidos activos",
    MessageKey.delivery_home_view_all_assigned to "Ver pedidos asignados",
    MessageKey.delivery_home_view_available to "Ver pedidos disponibles",
    MessageKey.delivery_home_retry to "Reintentar",
    MessageKey.delivery_home_active_empty to "No tenés pedidos activos en este momento.",
    MessageKey.delivery_home_pending to "Pendientes",
    MessageKey.delivery_home_in_progress to "En curso",
    MessageKey.delivery_home_delivered to "Entregados",
    MessageKey.delivery_home_eta to "ETA: {eta}",
    MessageKey.delivery_home_view_order to "Ir al pedido",
    MessageKey.delivery_home_quick_actions to "Accesos rápidos",
    MessageKey.delivery_tab_home to "Inicio",
    MessageKey.delivery_tab_orders to "Pedidos",
    MessageKey.delivery_tab_profile to "Perfil",
    MessageKey.delivery_order_status_pending to "Pendiente",
    MessageKey.delivery_order_status_in_progress to "En curso",
    MessageKey.delivery_order_status_delivered to "Entregado",
    MessageKey.client_entry_welcome_title to "Bienvenido a la tienda",
    MessageKey.client_entry_welcome_subtitle to "Ingresá para usar la aplicación",
    MessageKey.client_entry_register_button to "Registrarme",
    MessageKey.client_entry_login_button to "Ya tengo cuenta",
    MessageKey.client_entry_register_content_description to "Crear cuenta",
    MessageKey.client_entry_login_content_description to "Iniciar sesión",
    MessageKey.client_entry_account_info to "Tu cuenta se puede usar en otras tiendas de la plataforma.",
    MessageKey.client_entry_store_unavailable_message to "La tienda no está disponible por el momento.",
    MessageKey.client_entry_store_unavailable_secondary to "Volvé a intentarlo más tarde.",
    MessageKey.client_entry_store_unavailable_cta to "No es posible registrarse ahora",
    MessageKey.client_entry_store_unavailable_content_description to "Tienda cerrada",
    MessageKey.client_home_header_title to "Bienvenido",
    MessageKey.client_home_header_subtitle to "Explorá nuestro catálogo y realizá pedidos fácilmente.",
    MessageKey.client_home_header_description to "Armá tu pedido para {business} en pocos pasos.",
    MessageKey.client_home_cart_icon_content_description to "Carrito",
    MessageKey.client_home_delivery_title to "Entrega a domicilio",
    MessageKey.client_home_delivery_description to "{business} lleva tus compras a tu casa.",
    MessageKey.client_home_featured_title to "Productos destacados",
    MessageKey.client_home_featured_name to "Manzana roja",
    MessageKey.client_home_featured_price to "$1200 / kg",
    MessageKey.client_home_add_label to "Agregar",
    MessageKey.client_home_add_content_description to "Agregar al carrito",
    MessageKey.client_home_products_title to "Productos destacados",
    MessageKey.client_home_products_empty to "Todavía no hay productos disponibles en esta tienda.",
    MessageKey.client_home_products_error to "No pudimos cargar los productos. Reintentá más tarde.",
    MessageKey.client_home_retry to "Reintentar",
    MessageKey.client_home_added_to_cart to "Agregaste {product} al carrito.",
    MessageKey.client_home_orders_placeholder to "Tus pedidos estarán disponibles pronto.",
    MessageKey.client_home_tab_home to "Inicio",
    MessageKey.client_home_tab_orders to "Mis pedidos",
    MessageKey.client_home_tab_profile to "Perfil",
    MessageKey.client_cart_title to "Carrito",
    MessageKey.client_cart_subtitle to "Revisá los productos antes de confirmar tu pedido.",
    MessageKey.client_cart_summary_title to "Resumen",
    MessageKey.client_cart_subtotal_label to "Subtotal productos",
    MessageKey.client_cart_shipping_label to "Costo de envío estimado",
    MessageKey.client_cart_total_label to "Total",
    MessageKey.client_cart_continue to "Continuar pedido",
    MessageKey.client_cart_continue_placeholder to "Pronto podrás confirmar los datos de entrega.",
    MessageKey.client_cart_clear to "Vaciar carrito",
    MessageKey.client_cart_clear_confirmation to "¿Querés vaciar el carrito?",
    MessageKey.client_cart_clear_cancel to "Cancelar",
    MessageKey.client_cart_clear_confirm to "Vaciar",
    MessageKey.client_cart_empty_title to "Tu carrito está vacío.",
    MessageKey.client_cart_empty_subtitle to "Agregá productos desde la pantalla de Inicio.",
    MessageKey.client_cart_return_home to "Volver al inicio",
    MessageKey.client_cart_increase_quantity to "Aumentar cantidad",
    MessageKey.client_cart_decrease_quantity to "Reducir cantidad",
    MessageKey.client_cart_remove_item to "Eliminar producto del carrito",
    MessageKey.client_cart_item_subtotal to "Subtotal: {amount}",
    MessageKey.client_profile_title to "Perfil",
    MessageKey.client_profile_subtitle to "Gestioná tus datos y preferencias",
    MessageKey.client_profile_retry to "Reintentar",
    MessageKey.client_profile_loading to "Cargando perfil...",
    MessageKey.client_profile_personal_data to "Datos personales",
    MessageKey.client_profile_full_name to "Nombre completo",
    MessageKey.client_profile_email_label to "Correo electrónico",
    MessageKey.client_profile_phone_label to "Teléfono",
    MessageKey.client_profile_phone_invalid to "Ingresá un teléfono válido",
    MessageKey.client_profile_save_profile to "Guardar perfil",
    MessageKey.client_profile_save_profile_content_description to "Guardar cambios del perfil",
    MessageKey.client_profile_security_title to "Seguridad",
    MessageKey.client_profile_addresses_title to "Direcciones",
    MessageKey.client_profile_add_address to "Agregar dirección",
    MessageKey.client_profile_save_address to "Guardar dirección",
    MessageKey.client_profile_save_address_content_description to "Guardar dirección del cliente",
    MessageKey.client_profile_addresses_empty to "Aún no agregaste direcciones.",
    MessageKey.client_profile_default_badge to "Predeterminada",
    MessageKey.client_profile_delete_address to "Eliminar",
    MessageKey.client_profile_edit_address to "Editar",
    MessageKey.client_profile_make_default to "Marcar como predeterminada",
    MessageKey.client_profile_address_label to "Etiqueta",
    MessageKey.client_profile_address_line1 to "Dirección",
    MessageKey.client_profile_address_city to "Ciudad",
    MessageKey.client_profile_address_state to "Provincia/Estado",
    MessageKey.client_profile_address_zip to "Código postal",
    MessageKey.client_profile_address_country to "País",
    MessageKey.client_profile_preferences_title to "Preferencias",
    MessageKey.client_profile_language_label to "Idioma",
    MessageKey.client_profile_language_hint to "Elegí el idioma de la aplicación.",
    MessageKey.client_profile_language_es to "Español",
    MessageKey.client_profile_language_en to "Inglés",
    MessageKey.client_profile_saved to "Perfil actualizado",
    MessageKey.client_profile_address_saved to "Dirección guardada",
    MessageKey.client_profile_address_deleted to "Dirección eliminada",
    MessageKey.change_password_current_password to "Contraseña actual",
    MessageKey.change_password_submit to "Actualizar contraseña",
    MessageKey.change_password_success to "Contraseña actualizada",
    MessageKey.confirm_password_recovery to "Confirmar recuperación",
    MessageKey.email to "Correo electrónico",
    MessageKey.confirm_password_recovery_code to "Código",
    MessageKey.confirm_password_recovery_email to "Correo electrónico",
    MessageKey.confirm_password_recovery_success to "Contraseña actualizada",
    MessageKey.error_generic to "Ocurrió un error. Intentá nuevamente.",
    MessageKey.form_error_required to "Campo obligatorio",
    MessageKey.form_error_invalid_email to "Correo inválido",
    MessageKey.family_name to "Apellido",
    MessageKey.login_button to "Ingresar",
    MessageKey.login_change_password_description to "Tu cuenta requiere actualizar la contraseña antes de ingresar.",
    MessageKey.login_change_password_required to "Actualizá tu contraseña para continuar",
    MessageKey.login_change_password_title to "Actualizá tu contraseña",
    MessageKey.login_email_placeholder to "correo@intrale.com",
    MessageKey.login_error_credentials to "Usuario o contraseña incorrectos",
    MessageKey.login_family_name_placeholder to "Apellido",
    MessageKey.login_generic_error to "Ocurrió un error al iniciar sesión. Intentá nuevamente.",
    MessageKey.login_name_placeholder to "Nombre",
    MessageKey.login_new_password_placeholder to "Nueva contraseña segura",
    MessageKey.login_business_title to "Ingresá como administrador de negocio",
    MessageKey.login_business_subtitle to "Usá tus credenciales para acceder al panel, tu equipo y los pedidos de tu tienda.",
    MessageKey.login_password_icon_content_description to "Ícono de contraseña",
    MessageKey.login_password_placeholder to "Tu contraseña",
    MessageKey.login_subtitle to "Ingresá con tu correo corporativo para continuar.",
    MessageKey.login_title to "Ingresá a tu cuenta",
    MessageKey.login_delivery_subtitle to "Autenticá tu cuenta de repartidor para comenzar.",
    MessageKey.login_delivery_title to "Ingresá como repartidor",
    MessageKey.login_user_icon_content_description to "Ícono de usuario",
    MessageKey.first_name to "Nombre",
    MessageKey.new_password to "Nueva contraseña",
    MessageKey.password to "Contraseña",
    MessageKey.password_recovery to "Recuperar contraseña",
    MessageKey.password_recovery_have_code to "Ya tengo un código de recuperación",
    MessageKey.password_recovery_email_sent to "Correo enviado",
    MessageKey.business to "Negocio",
    MessageKey.request_join_business to "Solicitar unión",
    MessageKey.request_join_business_sent to "Solicitud enviada",
    MessageKey.review_join_business to "Revisar solicitudes de unión",
    MessageKey.review_join_business_action_approve to "Aprobar",
    MessageKey.review_join_business_action_reject to "Rechazar",
    MessageKey.review_join_business_feedback_approved to "Unión aprobada",
    MessageKey.review_join_business_feedback_rejected to "Unión rechazada",
    MessageKey.review_business_pending_requests to "Solicitudes pendientes",
    MessageKey.review_business_select_all to "Seleccionar todo",
    MessageKey.review_business_description_label to "Descripción",
    MessageKey.review_business_auto_accept_deliveries to "Auto acepta entregas",
    MessageKey.review_business_approve_selected to "Aprobar seleccionados",
    MessageKey.review_business_reject_selected to "Rechazar seleccionados",
    MessageKey.register_business to "Registrar negocio",
    MessageKey.register_business_success to "Solicitud enviada",
    MessageKey.business_name to "Nombre del negocio",
    MessageKey.business_description to "Descripción del negocio",
    MessageKey.business_admin_email to "Correo del administrador",
    MessageKey.register_saler_title to "Registrar vendedor",
    MessageKey.register_saler_submit to "Registrar vendedor",
    MessageKey.register_saler_success to "Registro enviado",
    MessageKey.register_saler_email_invalid to "Ingresá un correo electrónico válido",
    MessageKey.signup to "Registrarme",
    MessageKey.signup_platform_admin_title to "Registro administrador de plataforma",
    MessageKey.signup_platform_admin_submit to "Registrar administrador",
    MessageKey.signup_platform_admin to "Registro Platform Admin",
    MessageKey.signup_delivery to "Registro Delivery",
    MessageKey.delivery_request_access to "Solicitar alta",
    MessageKey.signup_delivery_title to "Registro Delivery",
    MessageKey.signup_delivery_submit to "Registrar repartidor",
    MessageKey.text_field_hide_password to "Ocultar contraseña",
    MessageKey.text_field_show_password to "Mostrar contraseña",
    MessageKey.username to "Usuario",
    MessageKey.delivery_dashboard_title to "Panel de repartidor",
    MessageKey.delivery_dashboard_subtitle to "Tu sesión está activa. Próximamente verás tus pedidos y rutas aquí.",
    MessageKey.delivery_dashboard_profile_cta to "Ver perfil de repartidor",
    MessageKey.delivery_profile_title to "Perfil de repartidor",
    MessageKey.delivery_profile_subtitle to "Revisá tus datos y zonas asignadas.",
    MessageKey.delivery_profile_full_name to "Nombre y apellido",
    MessageKey.delivery_profile_email to "Correo electrónico",
    MessageKey.delivery_profile_phone to "Teléfono de contacto",
    MessageKey.delivery_profile_vehicle_type to "Tipo de vehículo",
    MessageKey.delivery_profile_vehicle_model to "Marca y modelo",
    MessageKey.delivery_profile_vehicle_plate to "Patente (opcional)",
    MessageKey.delivery_profile_save to "Guardar perfil",
    MessageKey.delivery_profile_save_content_description to "Guardar datos del perfil de repartidor",
    MessageKey.delivery_profile_logout to "Cerrar sesión",
    MessageKey.delivery_profile_contact_title to "Datos de contacto",
    MessageKey.delivery_profile_vehicle_title to "Datos del vehículo",
    MessageKey.delivery_profile_zones_title to "Zonas asignadas",
    MessageKey.delivery_profile_zones_empty to "Todavía no tenés zonas asignadas.",
    MessageKey.delivery_profile_saved to "Perfil actualizado",
    MessageKey.two_factor_verify_submit to "Verificar código",
    MessageKey.two_factor_verify_success to "Código verificado",
)
