package ar.com.intrale.strings.catalog

import ar.com.intrale.strings.model.MessageKey

internal val DefaultCatalog_en: Map<MessageKey, String> = mapOf(
    MessageKey.app_name to "Intrale",
    MessageKey.buttons_preview_login to "Sign in",
    MessageKey.buttons_preview_logout to "Sign out",
    MessageKey.buttons_preview_signup to "Create account",
    MessageKey.buttons_preview_title to "Buttons preview",
    MessageKey.dashboard_title to "Main dashboard",
    MessageKey.dashboard_menu_hint to "Open the menu to access the main actions.",
    MessageKey.dashboard_menu_open_description to "Menu. Swipe right to go back. Swipe down to open. Tap to open or close.",
    MessageKey.dashboard_menu_close_description to "Close action menu",
    MessageKey.dashboard_menu_long_press_hint to "Swipe right to go back and down to open",
    MessageKey.dashboard_menu_buttons_preview to "Intrale buttons demo",
    MessageKey.dashboard_menu_title to "My account",
    MessageKey.dashboard_menu_change_password to "Change password",
    MessageKey.dashboard_menu_setup_two_factor to "Set up two-factor authentication",
    MessageKey.dashboard_menu_verify_two_factor to "Verify two-factor authentication",
    MessageKey.dashboard_menu_personalization to "Personalization",
    MessageKey.dashboard_business_header to "Business: {business}",
    MessageKey.dashboard_business_header_empty to "No business selected",
    MessageKey.dashboard_business_selector_label to "Select a business",
    MessageKey.dashboard_business_loading to "Loading businesses...",
    MessageKey.dashboard_business_error to "We couldn't load your businesses.",
    MessageKey.dashboard_business_missing to "Select a business to see the metrics.",
    MessageKey.dashboard_summary_loading to "Loading dashboard metrics...",
    MessageKey.dashboard_summary_error to "We couldn't load dashboard metrics.",
    MessageKey.dashboard_summary_retry to "Retry",
    MessageKey.dashboard_admin_subtitle to "Admin panel",
    MessageKey.dashboard_manage_intro to "Manage products, orders and your team from one place.",
    MessageKey.dashboard_card_products_title to "Products",
    MessageKey.dashboard_card_products_description to "Create, edit and publish the products your customers will see.",
    MessageKey.dashboard_card_products_metric to "{count} products loaded",
    MessageKey.dashboard_card_products_cta to "Manage products",
    MessageKey.dashboard_card_products_cta_catalog to "View catalog",
    MessageKey.dashboard_card_products_cta_add to "Add product",
    MessageKey.dashboard_card_orders_title to "Orders",
    MessageKey.dashboard_card_orders_description to "Review and manage received orders.",
    MessageKey.dashboard_card_orders_metric to "{count} pending orders",
    MessageKey.dashboard_card_orders_cta to "View orders",
    MessageKey.dashboard_card_orders_cta_pending to "Pending orders",
    MessageKey.dashboard_card_orders_cta_history to "Order history",
    MessageKey.dashboard_card_delivery_title to "Delivery",
    MessageKey.dashboard_card_delivery_description to "Set up your couriers and their assignments.",
    MessageKey.dashboard_card_delivery_metric to "{count} active couriers",
    MessageKey.dashboard_card_delivery_cta to "Manage delivery",
    MessageKey.dashboard_card_delivery_cta_drivers to "View couriers",
    MessageKey.dashboard_card_delivery_cta_invite to "Invite courier",
    MessageKey.dashboard_card_settings_title to "Settings",
    MessageKey.dashboard_card_settings_description to "Contact info, schedules, payment methods, banners.",
    MessageKey.dashboard_card_settings_metric to "Settings and personalization",
    MessageKey.dashboard_card_settings_cta to "Edit settings",
    MessageKey.personalization_title to "Personalization",
    MessageKey.personalization_access_denied to "You don't have permission to access this section",
    MessageKey.personalization_business_context to "Current business: {businessId}",
    MessageKey.personalization_description to "Customize your business appearance",
    MessageKey.personalization_section_pending to "Coming soon",
    MessageKey.personalization_section_colors to "Colors",
    MessageKey.personalization_section_typography to "Typography",
    MessageKey.personalization_section_images to "Images",
    MessageKey.personalization_section_app_icon to "App icon",
    MessageKey.personalization_section_preview to "Preview",
    MessageKey.dashboard_menu_business_products to "Products",
    MessageKey.dashboard_menu_business_categories to "Categories",
    MessageKey.business_products_title to "Products",
    MessageKey.business_products_add_action to "Add product",
    MessageKey.business_products_filter_all to "All",
    MessageKey.business_products_filter_published to "Published",
    MessageKey.business_products_filter_drafts to "Drafts",
    MessageKey.business_products_filter_category to "Filter by category",
    MessageKey.business_products_empty to "You do not have products yet.",
    MessageKey.business_products_error to "We could not load products. Please try again.",
    MessageKey.business_products_retry to "Retry",
    MessageKey.business_products_status_published to "Published",
    MessageKey.business_products_status_draft to "Draft",
    MessageKey.business_products_status_unknown to "Unknown status",
    MessageKey.business_products_access_denied to "Select a business and ensure you have admin permissions to view products.",
    MessageKey.product_list_missing_business to "Select a business to manage products.",
    MessageKey.product_form_title_create to "New product",
    MessageKey.product_form_title_edit to "Edit product",
    MessageKey.product_form_name to "Product name",
    MessageKey.product_form_short_description to "Short description",
    MessageKey.product_form_base_price to "Base price",
    MessageKey.product_form_unit to "Unit",
    MessageKey.product_form_category to "Category",
    MessageKey.product_form_status to "Status",
    MessageKey.product_form_save to "Save",
    MessageKey.product_form_delete to "Delete product",
    MessageKey.product_form_delete_confirm_title to "Delete product",
    MessageKey.product_form_delete_confirm_message to "Are you sure you want to delete this product?",
    MessageKey.product_form_delete_confirm_accept to "Delete",
    MessageKey.product_form_delete_confirm_cancel to "Cancel",
    MessageKey.product_form_error_invalid_price to "Enter a valid price greater than 0",
    MessageKey.product_form_missing_business to "You need to select a business to continue.",
    MessageKey.product_form_saved to "Product saved",
    MessageKey.product_form_deleted to "Product deleted",
    MessageKey.product_form_category_empty to "No categories available. Refresh the catalog to continue.",
    MessageKey.product_form_availability to "Availability",
    MessageKey.product_form_available to "Available",
    MessageKey.product_form_out_of_stock to "Out of stock",
    MessageKey.product_form_stock_quantity to "Stock quantity",
    MessageKey.product_form_stock_helper to "Leave empty for unlimited stock",
    MessageKey.business_products_out_of_stock to "Out of stock",
    MessageKey.client_product_out_of_stock to "Out of stock",
    MessageKey.business_categories_title to "Categories",
    MessageKey.business_categories_add_action to "Add category",
    MessageKey.business_categories_empty to "There are no categories yet.",
    MessageKey.business_categories_error to "We could not load categories. Please try again.",
    MessageKey.business_categories_retry to "Refresh categories",
    MessageKey.business_categories_access_denied to "You need business admin permissions to view categories.",
    MessageKey.business_categories_products_count to "Linked products: {count}",
    MessageKey.business_categories_edit to "Edit",
    MessageKey.business_categories_delete to "Delete",
    MessageKey.category_list_missing_business to "Select a business to view categories.",
    MessageKey.category_form_title_create to "New category",
    MessageKey.category_form_title_edit to "Edit category",
    MessageKey.category_form_name to "Category name",
    MessageKey.category_form_description to "Description",
    MessageKey.category_form_save to "Save",
    MessageKey.category_form_delete to "Delete category",
    MessageKey.category_form_delete_confirm_title to "Delete category",
    MessageKey.category_form_delete_confirm_message to "Are you sure you want to delete this category?",
    MessageKey.category_form_delete_confirm_accept to "Delete",
    MessageKey.category_form_delete_confirm_cancel to "Cancel",
    MessageKey.category_form_saved to "Category saved",
    MessageKey.category_form_deleted to "Category deleted",
    MessageKey.dashboard_menu_request_join_business to "Request to join",
    MessageKey.dashboard_menu_review_business_requests to "Review pending business requests",
    MessageKey.dashboard_menu_review_join_requests to "Review join requests",
    MessageKey.dashboard_menu_register_saler to "Register seller",
    MessageKey.dashboard_menu_logout to "Sign out",
    MessageKey.app_back_button to "Go back",
    MessageKey.app_home_icon_content_description to "Go to home",
    MessageKey.app_missing_title to "Screen without title",
    MessageKey.home_title to "Home",
    MessageKey.home_headline to "We boost your operation with Intrale",
    MessageKey.home_subtitle to "Sign in or sign up to centralize your business and manage your commercial network.",
    MessageKey.business_onboarding_title to "Run your business with Intrale",
    MessageKey.business_onboarding_subtitle to "Manage your orders, team and products from a single place.",
    MessageKey.business_onboarding_value_store_title to "Control your store",
    MessageKey.business_onboarding_value_store_description to "Centralize catalog, openings, and key actions for every location.",
    MessageKey.business_onboarding_value_team_title to "Manage your team",
    MessageKey.business_onboarding_value_team_description to "Invite admins and couriers with roles and permissions tailored to your business.",
    MessageKey.business_onboarding_value_monitor_title to "Monitor orders and dashboard",
    MessageKey.business_onboarding_value_monitor_description to "Track orders in real time and adjust your business settings from the dashboard.",
    MessageKey.delivery_home_title to "Delivery home",
    MessageKey.delivery_home_headline to "Welcome, delivery partner",
    MessageKey.delivery_home_subtitle to "Sign in with your credentials or request access to join the business.",
    MessageKey.delivery_home_greeting to "Hello, delivery partner",
    MessageKey.delivery_home_today to "Today is {date}",
    MessageKey.delivery_home_summary_title to "Day summary",
    MessageKey.delivery_home_active_title to "Active orders",
    MessageKey.delivery_home_view_all_assigned to "View assigned orders",
    MessageKey.delivery_home_view_available to "View available orders",
    MessageKey.delivery_home_retry to "Retry",
    MessageKey.delivery_home_active_empty to "You have no active orders right now.",
    MessageKey.delivery_home_pending to "Pending",
    MessageKey.delivery_home_in_progress to "In progress",
    MessageKey.delivery_home_delivered to "Delivered",
    MessageKey.delivery_home_eta to "ETA: {eta}",
    MessageKey.delivery_home_view_order to "Open order",
    MessageKey.delivery_home_quick_actions to "Quick actions",
    MessageKey.delivery_tab_home to "Home",
    MessageKey.delivery_tab_orders to "Orders",
    MessageKey.delivery_tab_profile to "Profile",
    MessageKey.delivery_order_status_pending to "Pending",
    MessageKey.delivery_order_status_in_progress to "In progress",
    MessageKey.delivery_order_status_delivered to "Delivered",
    MessageKey.client_entry_welcome_title to "Welcome to the store",
    MessageKey.client_entry_welcome_subtitle to "Sign in to use the app",
    MessageKey.client_entry_register_button to "Sign up",
    MessageKey.client_entry_login_button to "I already have an account",
    MessageKey.client_entry_register_content_description to "Create account",
    MessageKey.client_entry_login_content_description to "Sign in",
    MessageKey.client_entry_account_info to "Your account works across other stores in the platform.",
    MessageKey.client_entry_store_unavailable_message to "The store is not available right now.",
    MessageKey.client_entry_store_unavailable_secondary to "Please try again later.",
    MessageKey.client_entry_store_unavailable_cta to "Sign up is unavailable now",
    MessageKey.client_entry_store_unavailable_content_description to "Store closed",
    MessageKey.client_home_header_title to "Welcome",
    MessageKey.client_home_header_subtitle to "Explore our catalog and place orders with ease.",
    MessageKey.client_home_header_description to "Build your order for {business} in just a few steps.",
    MessageKey.client_home_cart_icon_content_description to "Cart",
    MessageKey.client_home_delivery_title to "Home delivery",
    MessageKey.client_home_delivery_description to "{business} delivers your purchases to your home.",
    MessageKey.client_home_delivery_cta to "Order now",
    MessageKey.client_home_view_catalog to "View full catalog",
    MessageKey.client_home_featured_title to "Featured products",
    MessageKey.client_home_featured_name to "Red apple",
    MessageKey.client_home_featured_price to "$1200 / kg",
    MessageKey.client_home_add_label to "Add",
    MessageKey.client_home_add_content_description to "Add to cart",
    MessageKey.client_home_products_title to "Featured products",
    MessageKey.client_home_products_empty to "There are no products available in this store yet.",
    MessageKey.client_home_products_error to "We couldn't load the products. Try again later.",
    MessageKey.client_home_retry to "Retry",
    MessageKey.client_home_added_to_cart to "Added {product} to your cart.",
    MessageKey.client_home_orders_placeholder to "Your orders section will be available soon.",
    MessageKey.client_home_tab_home to "Home",
    MessageKey.client_home_tab_orders to "My orders",
    MessageKey.client_home_tab_profile to "Profile",
    MessageKey.client_orders_title to "My orders",
    MessageKey.client_orders_empty to "You don't have any orders yet. They will appear here after your first purchase.",
    MessageKey.client_orders_loading to "Loading orders...",
    MessageKey.client_orders_error to "Could not load orders",
    MessageKey.client_orders_retry to "Retry",
    MessageKey.client_orders_order_date to "Date",
    MessageKey.client_orders_order_items to "items",
    MessageKey.client_orders_detail_title to "Order detail",
    MessageKey.client_orders_detail_items_title to "Products",
    MessageKey.client_orders_detail_address_title to "Delivery address",
    MessageKey.client_orders_filter_all to "All",
    MessageKey.client_orders_status_pending to "Pending",
    MessageKey.client_orders_status_confirmed to "Confirmed",
    MessageKey.client_orders_status_preparing to "Preparing",
    MessageKey.client_orders_status_ready to "Ready",
    MessageKey.client_orders_status_delivering to "Delivering",
    MessageKey.client_orders_status_delivered to "Delivered",
    MessageKey.client_orders_status_cancelled to "Cancelled",
    MessageKey.client_cart_title to "Cart",
    MessageKey.client_cart_subtitle to "Review the products before confirming your order.",
    MessageKey.client_cart_summary_title to "Summary",
    MessageKey.client_cart_subtotal_label to "Items subtotal",
    MessageKey.client_cart_shipping_label to "Estimated delivery cost",
    MessageKey.client_cart_total_label to "Total",
    MessageKey.client_cart_continue to "Continue order",
    MessageKey.client_cart_continue_placeholder to "We'll guide you to confirmation soon.",
    MessageKey.client_cart_clear to "Empty cart",
    MessageKey.client_cart_clear_confirmation to "Do you want to empty the cart?",
    MessageKey.client_cart_clear_cancel to "Cancel",
    MessageKey.client_cart_clear_confirm to "Empty",
    MessageKey.client_cart_empty_title to "Your cart is empty.",
    MessageKey.client_cart_empty_subtitle to "Add products from the Home screen.",
    MessageKey.client_cart_return_home to "Back to home",
    MessageKey.client_cart_increase_quantity to "Increase quantity",
    MessageKey.client_cart_decrease_quantity to "Decrease quantity",
    MessageKey.client_cart_remove_item to "Remove item from cart",
    MessageKey.client_cart_item_subtotal to "Subtotal: {amount}",
    MessageKey.client_cart_delivery_address_title to "Delivery address",
    MessageKey.client_cart_delivery_address_empty to "You haven't selected a delivery address yet.",
    MessageKey.client_cart_delivery_address_manage to "Manage addresses",
    MessageKey.client_cart_delivery_address_loading to "Loading saved addresses...",
    MessageKey.client_cart_continue_missing_address to "Add an address in your profile to continue.",
    MessageKey.client_cart_continue_with_address to "We'll use \"{label}\" as the delivery address.",
    MessageKey.client_profile_title to "Profile",
    MessageKey.client_profile_subtitle to "Manage your information and preferences",
    MessageKey.client_profile_retry to "Retry",
    MessageKey.client_profile_loading to "Loading profile...",
    MessageKey.client_profile_personal_data to "Personal data",
    MessageKey.client_profile_full_name to "Full name",
    MessageKey.client_profile_email_label to "Email",
    MessageKey.client_profile_phone_label to "Phone",
    MessageKey.client_profile_phone_invalid to "Enter a valid phone number",
    MessageKey.client_profile_save_profile to "Save profile",
    MessageKey.client_profile_save_profile_content_description to "Save profile changes",
    MessageKey.client_profile_security_title to "Security",
    MessageKey.client_profile_addresses_title to "Addresses",
    MessageKey.client_profile_add_address to "Add address",
    MessageKey.client_profile_save_address to "Save address",
    MessageKey.client_profile_save_address_content_description to "Save client address",
    MessageKey.client_profile_addresses_empty to "You have not added addresses yet.",
    MessageKey.client_profile_default_badge to "Default",
    MessageKey.client_profile_delete_address to "Delete",
    MessageKey.client_profile_edit_address to "Edit",
    MessageKey.client_profile_make_default to "Set as default",
    MessageKey.client_profile_address_label to "Label",
    MessageKey.client_profile_address_line1 to "Address",
    MessageKey.client_profile_address_number to "Number",
    MessageKey.client_profile_address_reference to "Reference",
    MessageKey.client_profile_address_city to "City",
    MessageKey.client_profile_address_state to "State/Province",
    MessageKey.client_profile_address_zip to "Postal code",
    MessageKey.client_profile_address_country to "Country",
    MessageKey.client_profile_preferences_title to "Preferences",
    MessageKey.client_profile_language_label to "Language",
    MessageKey.client_profile_language_hint to "Choose the language for the app.",
    MessageKey.client_profile_language_es to "Spanish",
    MessageKey.client_profile_language_en to "English",
    MessageKey.client_profile_saved to "Profile updated",
    MessageKey.client_profile_address_saved to "Address saved",
    MessageKey.client_profile_address_deleted to "Address deleted",
    MessageKey.client_addresses_error to "We couldn't load addresses",
    MessageKey.client_addresses_retry to "Retry",
    MessageKey.client_addresses_delete_confirm_title to "Delete address",
    MessageKey.client_addresses_delete_confirm_message to "Are you sure you want to delete this address?",
    MessageKey.client_addresses_delete_confirm_accept to "Delete",
    MessageKey.client_addresses_delete_confirm_cancel to "Cancel",
    MessageKey.client_address_form_title_create to "New address",
    MessageKey.client_address_form_title_edit to "Edit address",
    MessageKey.change_password_current_password to "Current password",
    MessageKey.change_password_submit to "Update password",
    MessageKey.change_password_success to "Password updated",
    MessageKey.confirm_password_recovery to "Confirm recovery",
    MessageKey.confirm_password_recovery_title to "Confirm recovery",
    MessageKey.confirm_password_recovery_subtitle to "Enter the code you received and your new password",
    MessageKey.confirm_password_recovery_confirm_password to "Confirm password",
    MessageKey.confirm_password_recovery_save to "Save new password",
    MessageKey.email to "Email",
    MessageKey.confirm_password_recovery_code to "Code",
    MessageKey.confirm_password_recovery_email to "Email",
    MessageKey.confirm_password_recovery_success to "Password updated",
    MessageKey.confirm_signup to "Confirm sign up",
    MessageKey.confirm_signup_title to "Confirm your account",
    MessageKey.confirm_signup_code to "Verification code",
    MessageKey.confirm_signup_submit to "Confirm",
    MessageKey.confirm_signup_resend to "Resend code",
    MessageKey.confirm_signup_success to "Account confirmed successfully",
    MessageKey.error_generic to "Something went wrong. Please try again.",
    MessageKey.form_error_required to "Required field",
    MessageKey.form_error_invalid_email to "Invalid email",
    MessageKey.form_error_invalid_code to "Code must be 6 digits",
    MessageKey.form_error_min_length_8 to "Must contain at least 8 characters",
    MessageKey.form_error_passwords_mismatch to "Passwords do not match",
    MessageKey.family_name to "Last name",
    MessageKey.login_button to "Sign in",
    MessageKey.login_change_password_description to "Your account must update the password before signing in.",
    MessageKey.login_change_password_required to "Update your password to continue",
    MessageKey.login_change_password_title to "Update your password",
    MessageKey.login_email_placeholder to "email@intrale.com",
    MessageKey.login_error_credentials to "Incorrect username or password",
    MessageKey.login_error_user_blocked to "Your user is blocked. Contact the business administrator.",
    MessageKey.login_family_name_placeholder to "Last name",
    MessageKey.login_generic_error to "There was an error while signing in. Try again.",
    MessageKey.login_name_placeholder to "First name",
    MessageKey.login_new_password_placeholder to "Secure new password",
    MessageKey.login_appbar_title to "Sign in",
    MessageKey.login_business_title to "Sign in as business admin",
    MessageKey.login_business_subtitle to "Use your business credentials to access the dashboard, team, and orders.",
    MessageKey.login_password_icon_content_description to "Password icon",
    MessageKey.login_password_placeholder to "Your password",
    MessageKey.login_subtitle to "Sign in with your corporate email to continue.",
    MessageKey.login_checking_session to "Verifying session...",
    MessageKey.login_title to "Sign in to your account",
    MessageKey.login_delivery_subtitle to "Authenticate your delivery account to start.",
    MessageKey.login_delivery_title to "Sign in as delivery driver",
    MessageKey.login_user_icon_content_description to "User icon",
    MessageKey.first_name to "Name",
    MessageKey.new_password to "New password",
    MessageKey.password to "Password",
    MessageKey.login_forgot_password to "Forgot your password?",
    MessageKey.login_no_account_divider to "Don't have an account?",
    MessageKey.login_advanced_options_divider to "Advanced options",
    MessageKey.login_delivery_driver_divider to "Are you a delivery driver?",
    MessageKey.password_recovery to "Recover password",
    MessageKey.password_recovery_title to "Recover password",
    MessageKey.password_recovery_subtitle to "Enter your email and we will send you a recovery code",
    MessageKey.password_recovery_send_code to "Send code",
    MessageKey.password_recovery_have_code to "I already have a recovery code",
    MessageKey.password_recovery_email_sent to "We sent you an email with instructions to continue",
    MessageKey.password_recovery_resend_code to "Resend code",
    MessageKey.business to "Business",
    MessageKey.request_join_business to "Request to join",
    MessageKey.request_join_business_sent to "Request sent",
    MessageKey.review_join_business to "Review join requests",
    MessageKey.review_join_business_action_approve to "Approve",
    MessageKey.review_join_business_action_reject to "Reject",
    MessageKey.review_join_business_feedback_approved to "Join request approved",
    MessageKey.review_join_business_feedback_rejected to "Join request rejected",
    MessageKey.review_business_pending_requests to "Pending requests",
    MessageKey.review_business_select_all to "Select all",
    MessageKey.review_business_description_label to "Description",
    MessageKey.review_business_auto_accept_deliveries to "Auto-accept deliveries",
    MessageKey.review_business_approve_selected to "Approve selected",
    MessageKey.review_business_reject_selected to "Reject selected",
    MessageKey.review_business_feedback_approved to "Business approved",
    MessageKey.review_business_feedback_rejected to "Business rejected",
    MessageKey.review_business_no_pending to "No pending requests",
    MessageKey.register_business to "Register business",
    MessageKey.register_business_success to "Request sent",
    MessageKey.business_name to "Business name",
    MessageKey.business_description to "Business description",
    MessageKey.business_admin_email to "Administrator email",
    MessageKey.register_saler_title to "Register seller",
    MessageKey.register_saler_submit to "Register seller",
    MessageKey.register_saler_success to "Registration sent",
    MessageKey.register_saler_email_invalid to "Enter a valid email address",
    MessageKey.signup to "Sign up",
    MessageKey.signup_platform_admin_title to "Platform admin signup",
    MessageKey.signup_platform_admin_submit to "Register platform admin",
    MessageKey.signup_platform_admin to "Platform admin signup",
    MessageKey.signup_delivery to "Delivery signup",
    MessageKey.signup_select_subtitle to "Choose your account type",
    MessageKey.signup_platform_admin_description to "Manage your business, products, pricing and sales from a single platform.",
    MessageKey.signup_delivery_description to "Sign up as a delivery driver to receive and manage delivery orders.",
    MessageKey.delivery_request_access to "Request access",
    MessageKey.signup_delivery_title to "Delivery signup",
    MessageKey.signup_delivery_submit to "Register delivery driver",
    MessageKey.text_field_hide_password to "Hide password",
    MessageKey.text_field_show_password to "Show password",
    MessageKey.username to "Username",
    MessageKey.delivery_dashboard_title to "Delivery dashboard",
    MessageKey.delivery_dashboard_subtitle to "Your session is active. You'll soon see your routes and orders here.",
    MessageKey.delivery_dashboard_profile_cta to "Open delivery profile",
    MessageKey.delivery_orders_title to "Assigned orders",
    MessageKey.delivery_orders_subtitle to "These are your pending and in-progress orders.",
    MessageKey.delivery_orders_empty to "You have no assigned orders right now.",
    MessageKey.delivery_orders_error to "Could not load orders.",
    MessageKey.delivery_orders_retry to "Retry",
    MessageKey.delivery_orders_loading to "Loading orders...",
    MessageKey.delivery_order_action_start to "Start delivery",
    MessageKey.delivery_order_action_deliver to "Mark delivered",
    MessageKey.delivery_order_action_problem to "Report problem",
    MessageKey.delivery_orders_filter_all to "All",
    MessageKey.delivery_order_status_updating to "Updating status...",
    MessageKey.delivery_order_status_updated to "Status updated",
    MessageKey.delivery_order_status_update_error to "Failed to update status",
    MessageKey.delivery_order_detail_title to "Order detail",
    MessageKey.delivery_order_detail_back to "Back",
    MessageKey.delivery_order_detail_loading to "Loading detail...",
    MessageKey.delivery_order_detail_error to "Could not load order detail.",
    MessageKey.delivery_order_detail_retry to "Retry",
    MessageKey.delivery_order_detail_no_selection to "No order selected.",
    MessageKey.delivery_order_detail_section_business to "Business",
    MessageKey.delivery_order_detail_section_customer to "Customer",
    MessageKey.delivery_order_detail_section_items to "Items",
    MessageKey.delivery_order_detail_section_payment to "Payment",
    MessageKey.delivery_order_detail_section_status to "Order status",
    MessageKey.delivery_order_detail_address to "Address",
    MessageKey.delivery_order_detail_address_notes to "References",
    MessageKey.delivery_order_detail_customer_name to "Name",
    MessageKey.delivery_order_detail_customer_phone to "Phone",
    MessageKey.delivery_order_detail_item_quantity to "x{quantity}",
    MessageKey.delivery_order_detail_item_notes to "Note: {notes}",
    MessageKey.delivery_order_detail_payment_method to "Payment method",
    MessageKey.delivery_order_detail_collect_on_delivery to "Collect on delivery",
    MessageKey.delivery_order_detail_collect_on_delivery_yes to "Yes, collect on delivery",
    MessageKey.delivery_order_detail_collect_on_delivery_no to "No, already paid",
    MessageKey.delivery_order_detail_eta to "Estimated time: {eta}",
    MessageKey.delivery_order_detail_distance to "Distance: {distance}",
    MessageKey.delivery_order_detail_notes to "Order notes",
    MessageKey.delivery_order_detail_items_count to "{count} item(s)",
    MessageKey.delivery_order_action_not_delivered to "Could not deliver",
    MessageKey.delivery_order_confirm_title to "Confirm delivery",
    MessageKey.delivery_order_confirm_message to "Confirm delivery of order {label}?",
    MessageKey.delivery_order_confirm_yes to "Yes, deliver",
    MessageKey.delivery_order_confirm_cancel to "Cancel",
    MessageKey.delivery_order_not_delivered_sheet_title to "Why could you not deliver?",
    MessageKey.delivery_order_not_delivered_reason_absent to "Customer absent",
    MessageKey.delivery_order_not_delivered_reason_wrong_address to "Wrong address",
    MessageKey.delivery_order_not_delivered_reason_rejected to "Customer rejected the order",
    MessageKey.delivery_order_not_delivered_reason_payment to "Payment issue",
    MessageKey.delivery_order_not_delivered_reason_other to "Other reason",
    MessageKey.delivery_order_not_delivered_other_hint to "Describe the reason...",
    MessageKey.delivery_order_not_delivered_reason_required to "Select a reason",
    MessageKey.delivery_order_not_delivered_other_required to "Describe the reason",
    MessageKey.delivery_order_not_delivered_success to "Delivery result recorded",
    MessageKey.delivery_order_status_not_delivered to "Not delivered",
    MessageKey.delivery_profile_title to "Delivery profile",
    MessageKey.delivery_profile_subtitle to "Review your info and assigned zones.",
    MessageKey.delivery_profile_full_name to "Full name",
    MessageKey.delivery_profile_email to "Email",
    MessageKey.delivery_profile_phone to "Contact phone",
    MessageKey.delivery_profile_vehicle_type to "Vehicle type",
    MessageKey.delivery_profile_vehicle_model to "Make and model",
    MessageKey.delivery_profile_vehicle_plate to "License plate (optional)",
    MessageKey.delivery_profile_save to "Save profile",
    MessageKey.delivery_profile_save_content_description to "Save delivery profile changes",
    MessageKey.delivery_profile_logout to "Sign out",
    MessageKey.delivery_profile_contact_title to "Contact information",
    MessageKey.delivery_profile_vehicle_title to "Vehicle details",
    MessageKey.delivery_profile_zones_title to "Assigned zones",
    MessageKey.delivery_profile_zones_empty to "No zones assigned yet.",
    MessageKey.delivery_profile_saved to "Profile updated",
    MessageKey.delivery_availability_title to "Availability",
    MessageKey.delivery_availability_subtitle to "Choose your availability by day and time zone.",
    MessageKey.delivery_availability_timezone to "Time zone",
    MessageKey.delivery_availability_mode_block to "Blocks",
    MessageKey.delivery_availability_mode_custom to "Custom",
    MessageKey.delivery_availability_block_morning to "Morning",
    MessageKey.delivery_availability_block_afternoon to "Afternoon",
    MessageKey.delivery_availability_block_night to "Night",
    MessageKey.delivery_availability_block_range_template to "Range: {start} - {end}",
    MessageKey.delivery_availability_start to "Start",
    MessageKey.delivery_availability_end to "End",
    MessageKey.delivery_availability_day_enabled to "Day enabled",
    MessageKey.delivery_availability_day_disabled to "Day disabled",
    MessageKey.delivery_availability_day_monday to "Monday",
    MessageKey.delivery_availability_day_tuesday to "Tuesday",
    MessageKey.delivery_availability_day_wednesday to "Wednesday",
    MessageKey.delivery_availability_day_thursday to "Thursday",
    MessageKey.delivery_availability_day_friday to "Friday",
    MessageKey.delivery_availability_day_saturday to "Saturday",
    MessageKey.delivery_availability_day_sunday to "Sunday",
    MessageKey.delivery_availability_error_timezone_required to "Please provide your time zone.",
    MessageKey.delivery_availability_error_no_days to "Enable at least one day of availability.",
    MessageKey.delivery_availability_error_block_required to "Choose a valid block.",
    MessageKey.delivery_availability_error_custom_range_missing to "Fill start and end times for the custom range.",
    MessageKey.delivery_availability_error_invalid_time to "Use the HH:mm format.",
    MessageKey.delivery_availability_error_end_before_start to "End time must be after start time.",
    MessageKey.delivery_availability_saved to "Availability updated",
    MessageKey.two_factor_verify_submit to "Verify code",
    MessageKey.two_factor_verify_success to "Code verified",
    MessageKey.client_catalog_title to "Catalog",
    MessageKey.client_catalog_subtitle to "Browse all available products.",
    MessageKey.client_catalog_search_placeholder to "Search products...",
    MessageKey.client_catalog_filter_all to "All",
    MessageKey.client_catalog_empty to "There are no products available right now.",
    MessageKey.client_catalog_error to "We couldn't load the catalog. Try again later.",
    MessageKey.client_catalog_retry to "Retry",
    MessageKey.client_catalog_add_label to "Add",
    MessageKey.client_catalog_add_content_description to "Add to cart",
    MessageKey.client_catalog_added_to_cart to "Added {product} to your cart.",
    MessageKey.client_catalog_search_no_results to "No products found matching your search.",
    MessageKey.client_onboarding_welcome_title to "Welcome to Intrale",
    MessageKey.client_onboarding_welcome_subtitle to "Your favorite store, now in your pocket.",
    MessageKey.client_onboarding_discover_title to "Discover products",
    MessageKey.client_onboarding_discover_description to "Browse the full catalog with categories and deals.",
    MessageKey.client_onboarding_order_title to "Place your order",
    MessageKey.client_onboarding_order_description to "Add products to your cart and confirm in a few steps.",
    MessageKey.client_onboarding_start_title to "Get started",
    MessageKey.client_onboarding_start_description to "Create your account or sign in to start shopping.",
    MessageKey.client_onboarding_next to "Next",
    MessageKey.client_onboarding_skip to "Skip",
    MessageKey.client_onboarding_start_button to "Get started",
    MessageKey.client_product_detail_title to "Product detail",
    MessageKey.client_product_detail_description_label to "Description",
    MessageKey.client_product_detail_price_label to "Price",
    MessageKey.client_product_detail_unit_label to "Unit",
    MessageKey.client_product_detail_stock_label to "Available stock",
    MessageKey.client_product_detail_stock_unavailable to "No info",
    MessageKey.client_product_detail_quantity_label to "Quantity",
    MessageKey.client_product_detail_add_to_cart to "Add to cart",
    MessageKey.client_product_detail_update_cart to "Update cart",
    MessageKey.client_product_detail_already_in_cart to "Already in your cart",
    MessageKey.client_product_detail_added_snackbar to "Added {product} to your cart.",
    MessageKey.client_product_detail_updated_snackbar to "Updated {product} in your cart.",
    MessageKey.client_product_detail_loading to "Loading product...",
    MessageKey.client_product_detail_error to "We couldn't load the product. Try again later.",
    MessageKey.client_product_detail_retry to "Retry",
    MessageKey.client_product_detail_back to "Back",
    MessageKey.typography_title to "Typography",
    MessageKey.typography_description to "Select the font for each text type in your business",
    MessageKey.typography_type_title to "Titles",
    MessageKey.typography_type_subtitle to "Subtitles",
    MessageKey.typography_type_body to "Body text",
    MessageKey.typography_type_button to "Buttons",
    MessageKey.typography_font_none to "Not selected",
    MessageKey.typography_save to "Save typography",
    MessageKey.typography_saved to "Typography saved successfully",
    MessageKey.typography_loading_error to "We could not load the typography settings. Please try again.",
    MessageKey.typography_preview_title to "Preview",
    MessageKey.typography_preview_sample_title to "Title sample",
    MessageKey.typography_preview_sample_subtitle to "Subtitle sample",
    MessageKey.typography_preview_sample_body to "Body text sample",
    MessageKey.typography_preview_sample_button to "BUTTON",
    MessageKey.typography_access_denied to "You do not have permission to configure typography",
    MessageKey.password_strength_weak to "Weak",
    MessageKey.password_strength_medium to "Medium",
    MessageKey.password_strength_strong to "Strong",
    MessageKey.password_strength_hint_weak to "Minimum 8 characters with letters and numbers",
    MessageKey.password_strength_hint_medium to "Add symbols for more security",
    MessageKey.password_strength_hint_strong to "Secure password",
    MessageKey.password_match to "Passwords match",
    MessageKey.password_no_match to "Passwords do not match",
    MessageKey.change_password_confirm_new_password to "Confirm new password",
    MessageKey.force_change_password_appbar_title to "Password Change",
    MessageKey.force_change_password_welcome_title to "Welcome!",
    MessageKey.force_change_password_security_message to "For security reasons, you must change your password before continuing.",
    MessageKey.force_change_password_continue to "Continue",
    MessageKey.business_orders_title to "Orders",
    MessageKey.business_orders_empty to "No orders yet",
    MessageKey.business_orders_error to "Could not load orders",
    MessageKey.business_orders_retry to "Retry",
    MessageKey.business_orders_filter_all to "All",
    MessageKey.business_orders_filter_today to "Today",
    MessageKey.business_orders_filter_last_7_days to "Last 7 days",
    MessageKey.business_orders_status_pending to "Pending",
    MessageKey.business_orders_status_confirmed to "Confirmed",
    MessageKey.business_orders_status_preparing to "Preparing",
    MessageKey.business_orders_status_ready to "Ready",
    MessageKey.business_orders_status_delivering to "On the way",
    MessageKey.business_orders_status_delivered to "Delivered",
    MessageKey.business_orders_status_cancelled to "Cancelled",
    MessageKey.dashboard_card_business_config_title to "Business data",
    MessageKey.dashboard_card_business_config_description to "Name, address, contact and logo",
    MessageKey.dashboard_card_business_config_metric to "Basic business configuration",
    MessageKey.dashboard_card_business_config_cta to "Edit data",
    MessageKey.business_config_title to "Business details",
    MessageKey.business_config_description to "Set up the basic details of your business",
    MessageKey.business_config_access_denied to "You do not have permission to access this section",
    MessageKey.business_config_loading to "Loading settings...",
    MessageKey.business_config_missing_business to "Select a business to view its settings",
    MessageKey.business_config_error to "We could not load the business settings",
    MessageKey.business_config_retry to "Retry",
    MessageKey.business_config_name to "Business name",
    MessageKey.business_config_address to "Main address",
    MessageKey.business_config_phone to "Phone / WhatsApp",
    MessageKey.business_config_email to "Email",
    MessageKey.business_config_logo_url to "Logo URL",
    MessageKey.business_config_save to "Save details",
    MessageKey.business_config_saved to "Details saved successfully",
    MessageKey.dashboard_menu_business_config to "Business details",
    MessageKey.dashboard_empty_title to "Your dashboard is ready",
    MessageKey.dashboard_empty_description to "No data to show yet. Start by adding your products.",
    MessageKey.dashboard_empty_products_hint to "Add products",
    MessageKey.dashboard_error_title to "Something went wrong",
    MessageKey.dashboard_error_description to "We couldn't load the dashboard information. Try again in a few seconds.",
    MessageKey.dashboard_summary_empty_title to "No recent activity",
    MessageKey.dashboard_summary_empty_description to "When you have products and orders, you'll see the metrics here.",
    MessageKey.dashboard_summary_empty_cta to "Go to products",
)
