package ar.com.intrale.strings.catalog

import ar.com.intrale.strings.model.MessageKey

internal val DefaultCatalog_es: Map<MessageKey, String> = mapOf(
    MessageKey.app_name to "Intrale",
    MessageKey.buttons_preview_login to "Iniciar sesión",
    MessageKey.buttons_preview_logout to "Cerrar sesión",
    MessageKey.buttons_preview_signup to "Crear cuenta",
    MessageKey.buttons_preview_title to "Vista previa de botones",
    MessageKey.dashboard_title to "Panel principal",
    MessageKey.dashboard_menu_hint to "Desplegá el menú para acceder a las acciones principales.",
    MessageKey.dashboard_menu_open_description to "Menú. Deslizá a la derecha para volver. Deslizá hacia abajo para abrir. Tocá para abrir o cerrar.",
    MessageKey.dashboard_menu_close_description to "Cerrar menú de acciones",
    MessageKey.dashboard_menu_long_press_hint to "Deslizá a la derecha para volver y hacia abajo para abrir",
    MessageKey.dashboard_menu_buttons_preview to "Demo de botones Intrale",
    MessageKey.dashboard_menu_change_password to "Cambiar contraseña",
    MessageKey.dashboard_menu_setup_two_factor to "Configurar autenticación en dos pasos",
    MessageKey.dashboard_menu_verify_two_factor to "Verificar autenticación en dos pasos",
    MessageKey.dashboard_menu_personalization to "Personalización",
    MessageKey.personalization_title to "Personalización",
    MessageKey.personalization_access_denied to "No tenés permiso para acceder a esta sección",
    MessageKey.personalization_business_context to "Negocio actual: {businessId}",
    MessageKey.personalization_description to "Configurá la apariencia de tu negocio",
    MessageKey.personalization_section_pending to "Disponible próximamente",
    MessageKey.personalization_section_colors to "Colores",
    MessageKey.personalization_section_typography to "Tipografías",
    MessageKey.personalization_section_images to "Imágenes",
    MessageKey.personalization_section_app_icon to "Ícono de app",
    MessageKey.personalization_section_preview to "Previsualización",
    MessageKey.dashboard_menu_request_join_business to "Solicitar unión",
    MessageKey.dashboard_menu_review_business_requests to "Revisar solicitudes de negocio pendientes",
    MessageKey.dashboard_menu_review_join_requests to "Revisar solicitudes de unión",
    MessageKey.dashboard_menu_register_saler to "Registrar vendedor",
    MessageKey.dashboard_menu_logout to "Salir",
    MessageKey.app_back_button to "Volver",
    MessageKey.app_home_icon_content_description to "Ir al inicio",
    MessageKey.app_missing_title to "Pantalla sin título",
    MessageKey.home_title to "Inicio",
    MessageKey.home_headline to "Impulsamos tu operación con Intrale",
    MessageKey.home_subtitle to "Ingresá o registrate para centralizar tu negocio y la gestión de tu red comercial.",
    MessageKey.client_entry_welcome_title to "Bienvenido a la tienda",
    MessageKey.client_entry_welcome_subtitle to "Ingresá para usar la aplicación",
    MessageKey.client_entry_register_button to "Registrarme",
    MessageKey.client_entry_login_button to "Ya tengo cuenta",
    MessageKey.client_entry_register_content_description to "Crear cuenta",
    MessageKey.client_entry_login_content_description to "Iniciar sesión",
    MessageKey.client_entry_account_info to "Tu cuenta se puede usar en otras tiendas de la plataforma.",
    MessageKey.client_entry_store_unavailable_message to "La tienda no está disponible por el momento.",
    MessageKey.client_entry_store_unavailable_secondary to "Volvé a intentarlo más tarde.",
    MessageKey.client_entry_store_unavailable_cta to "No es posible registrarse ahora",
    MessageKey.client_entry_store_unavailable_content_description to "Tienda cerrada",
    MessageKey.client_home_header_subtitle to "Clientes",
    MessageKey.client_home_cart_icon_content_description to "Carrito",
    MessageKey.client_home_delivery_title to "Entrega a domicilio",
    MessageKey.client_home_delivery_description to "{business} lleva tus compras a tu casa.",
    MessageKey.client_home_featured_title to "Productos destacados",
    MessageKey.client_home_featured_name to "Manzana roja",
    MessageKey.client_home_featured_price to "$1200 / kg",
    MessageKey.client_home_add_label to "Agregar",
    MessageKey.client_home_add_content_description to "Agregar al carrito",
    MessageKey.client_home_tab_home to "Inicio",
    MessageKey.client_home_tab_orders to "Mis pedidos",
    MessageKey.client_home_tab_profile to "Perfil",
    MessageKey.change_password_current_password to "Contraseña actual",
    MessageKey.change_password_submit to "Actualizar contraseña",
    MessageKey.change_password_success to "Contraseña actualizada",
    MessageKey.confirm_password_recovery to "Confirmar recuperación",
    MessageKey.email to "Correo electrónico",
    MessageKey.confirm_password_recovery_code to "Código",
    MessageKey.confirm_password_recovery_email to "Correo electrónico",
    MessageKey.confirm_password_recovery_success to "Contraseña actualizada",
    MessageKey.error_generic to "Ocurrió un error. Intentá nuevamente.",
    MessageKey.form_error_required to "Campo obligatorio",
    MessageKey.form_error_invalid_email to "Correo inválido",
    MessageKey.family_name to "Apellido",
    MessageKey.login_button to "Ingresar",
    MessageKey.login_change_password_description to "Tu cuenta requiere actualizar la contraseña antes de ingresar.",
    MessageKey.login_change_password_required to "Actualizá tu contraseña para continuar",
    MessageKey.login_change_password_title to "Actualizá tu contraseña",
    MessageKey.login_email_placeholder to "correo@intrale.com",
    MessageKey.login_error_credentials to "Usuario o contraseña incorrectos",
    MessageKey.login_family_name_placeholder to "Apellido",
    MessageKey.login_generic_error to "Ocurrió un error al iniciar sesión. Intentá nuevamente.",
    MessageKey.login_name_placeholder to "Nombre",
    MessageKey.login_new_password_placeholder to "Nueva contraseña segura",
    MessageKey.login_password_icon_content_description to "Ícono de contraseña",
    MessageKey.login_password_placeholder to "Tu contraseña",
    MessageKey.login_subtitle to "Ingresá con tu correo corporativo para continuar.",
    MessageKey.login_title to "Bienvenido a Intrale",
    MessageKey.login_user_icon_content_description to "Ícono de usuario",
    MessageKey.first_name to "Nombre",
    MessageKey.new_password to "Nueva contraseña",
    MessageKey.password to "Contraseña",
    MessageKey.password_recovery to "Recuperar contraseña",
    MessageKey.password_recovery_email_sent to "Correo enviado",
    MessageKey.business to "Negocio",
    MessageKey.request_join_business to "Solicitar unión",
    MessageKey.request_join_business_sent to "Solicitud enviada",
    MessageKey.review_join_business to "Revisar solicitudes de unión",
    MessageKey.review_join_business_action_approve to "Aprobar",
    MessageKey.review_join_business_action_reject to "Rechazar",
    MessageKey.review_join_business_feedback_approved to "Unión aprobada",
    MessageKey.review_join_business_feedback_rejected to "Unión rechazada",
    MessageKey.review_business_pending_requests to "Solicitudes pendientes",
    MessageKey.review_business_select_all to "Seleccionar todo",
    MessageKey.review_business_description_label to "Descripción",
    MessageKey.review_business_auto_accept_deliveries to "Auto acepta entregas",
    MessageKey.review_business_approve_selected to "Aprobar seleccionados",
    MessageKey.review_business_reject_selected to "Rechazar seleccionados",
    MessageKey.register_business to "Registrar negocio",
    MessageKey.register_business_success to "Solicitud enviada",
    MessageKey.business_name to "Nombre del negocio",
    MessageKey.business_description to "Descripción del negocio",
    MessageKey.business_admin_email to "Correo del administrador",
    MessageKey.register_saler_title to "Registrar vendedor",
    MessageKey.register_saler_submit to "Registrar vendedor",
    MessageKey.register_saler_success to "Registro enviado",
    MessageKey.register_saler_email_invalid to "Ingresá un correo electrónico válido",
    MessageKey.signup to "Registrarme",
    MessageKey.signup_platform_admin_title to "Registro administrador de plataforma",
    MessageKey.signup_platform_admin_submit to "Registrar administrador",
    MessageKey.signup_platform_admin to "Registro Platform Admin",
    MessageKey.signup_delivery to "Registro Delivery",
    MessageKey.signup_delivery_title to "Registro Delivery",
    MessageKey.signup_delivery_submit to "Registrar repartidor",
    MessageKey.text_field_hide_password to "Ocultar contraseña",
    MessageKey.text_field_show_password to "Mostrar contraseña",
    MessageKey.username to "Usuario",
    MessageKey.two_factor_verify_submit to "Verificar código",
    MessageKey.two_factor_verify_success to "Código verificado",
)
