package ar.com.intrale.strings.catalog

import ar.com.intrale.strings.model.MessageKey

internal val DefaultCatalog_en: Map<MessageKey, String> = mapOf(
    MessageKey.app_name to "Intrale",
    MessageKey.buttons_preview_login to "Sign in",
    MessageKey.buttons_preview_logout to "Sign out",
    MessageKey.buttons_preview_signup to "Create account",
    MessageKey.buttons_preview_title to "Buttons preview",
    MessageKey.dashboard_title to "Main dashboard",
    MessageKey.dashboard_menu_hint to "Open the menu to access the main actions.",
    MessageKey.dashboard_menu_open_description to "Menu. Swipe right to go back. Swipe down to open. Tap to open or close.",
    MessageKey.dashboard_menu_close_description to "Close action menu",
    MessageKey.dashboard_menu_long_press_hint to "Swipe right to go back and down to open",
    MessageKey.dashboard_menu_buttons_preview to "Intrale buttons demo",
    MessageKey.dashboard_menu_change_password to "Change password",
    MessageKey.dashboard_menu_setup_two_factor to "Set up two-factor authentication",
    MessageKey.dashboard_menu_verify_two_factor to "Verify two-factor authentication",
    MessageKey.dashboard_menu_personalization to "Personalization",
    MessageKey.personalization_title to "Personalization",
    MessageKey.personalization_access_denied to "You don't have permission to access this section",
    MessageKey.personalization_business_context to "Current business: {businessId}",
    MessageKey.personalization_description to "Customize your business appearance",
    MessageKey.personalization_section_pending to "Coming soon",
    MessageKey.personalization_section_colors to "Colors",
    MessageKey.personalization_section_typography to "Typography",
    MessageKey.personalization_section_images to "Images",
    MessageKey.personalization_section_app_icon to "App icon",
    MessageKey.personalization_section_preview to "Preview",
    MessageKey.dashboard_menu_request_join_business to "Request to join",
    MessageKey.dashboard_menu_review_business_requests to "Review pending business requests",
    MessageKey.dashboard_menu_review_join_requests to "Review join requests",
    MessageKey.dashboard_menu_register_saler to "Register seller",
    MessageKey.dashboard_menu_logout to "Sign out",
    MessageKey.app_back_button to "Go back",
    MessageKey.app_home_icon_content_description to "Go to home",
    MessageKey.app_missing_title to "Screen without title",
    MessageKey.home_title to "Home",
    MessageKey.home_headline to "We boost your operation with Intrale",
    MessageKey.home_subtitle to "Sign in or sign up to centralize your business and manage your commercial network.",
    MessageKey.client_entry_welcome_title to "Welcome to the store",
    MessageKey.client_entry_welcome_subtitle to "Sign in to use the app",
    MessageKey.client_entry_register_button to "Sign up",
    MessageKey.client_entry_login_button to "I already have an account",
    MessageKey.client_entry_register_content_description to "Create account",
    MessageKey.client_entry_login_content_description to "Sign in",
    MessageKey.client_entry_account_info to "Your account works across other stores in the platform.",
    MessageKey.client_entry_store_unavailable_message to "The store is not available right now.",
    MessageKey.client_entry_store_unavailable_secondary to "Please try again later.",
    MessageKey.client_entry_store_unavailable_cta to "Sign up is unavailable now",
    MessageKey.client_entry_store_unavailable_content_description to "Store closed",
    MessageKey.client_home_header_subtitle to "Customers",
    MessageKey.client_home_cart_icon_content_description to "Cart",
    MessageKey.client_home_delivery_title to "Home delivery",
    MessageKey.client_home_delivery_description to "{business} delivers your purchases to your home.",
    MessageKey.client_home_featured_title to "Featured products",
    MessageKey.client_home_featured_name to "Red apple",
    MessageKey.client_home_featured_price to "$1200 / kg",
    MessageKey.client_home_add_label to "Add",
    MessageKey.client_home_add_content_description to "Add to cart",
    MessageKey.client_home_tab_home to "Home",
    MessageKey.client_home_tab_orders to "My orders",
    MessageKey.client_home_tab_profile to "Profile",
    MessageKey.change_password_current_password to "Current password",
    MessageKey.change_password_submit to "Update password",
    MessageKey.change_password_success to "Password updated",
    MessageKey.confirm_password_recovery to "Confirm recovery",
    MessageKey.email to "Email",
    MessageKey.confirm_password_recovery_code to "Code",
    MessageKey.confirm_password_recovery_email to "Email",
    MessageKey.confirm_password_recovery_success to "Password updated",
    MessageKey.error_generic to "Something went wrong. Please try again.",
    MessageKey.form_error_required to "Required field",
    MessageKey.form_error_invalid_email to "Invalid email",
    MessageKey.family_name to "Last name",
    MessageKey.login_button to "Sign in",
    MessageKey.login_change_password_description to "Your account must update the password before signing in.",
    MessageKey.login_change_password_required to "Update your password to continue",
    MessageKey.login_change_password_title to "Update your password",
    MessageKey.login_email_placeholder to "email@intrale.com",
    MessageKey.login_error_credentials to "Incorrect username or password",
    MessageKey.login_family_name_placeholder to "Last name",
    MessageKey.login_generic_error to "There was an error while signing in. Try again.",
    MessageKey.login_name_placeholder to "First name",
    MessageKey.login_new_password_placeholder to "Secure new password",
    MessageKey.login_password_icon_content_description to "Password icon",
    MessageKey.login_password_placeholder to "Your password",
    MessageKey.login_subtitle to "Sign in with your corporate email to continue.",
    MessageKey.login_title to "Sign in to your account",
    MessageKey.login_user_icon_content_description to "User icon",
    MessageKey.first_name to "Name",
    MessageKey.new_password to "New password",
    MessageKey.password to "Password",
    MessageKey.password_recovery to "Recover password",
    MessageKey.password_recovery_have_code to "I already have a recovery code",
    MessageKey.password_recovery_email_sent to "Recovery email sent",
    MessageKey.business to "Business",
    MessageKey.request_join_business to "Request to join",
    MessageKey.request_join_business_sent to "Request sent",
    MessageKey.review_join_business to "Review join requests",
    MessageKey.review_join_business_action_approve to "Approve",
    MessageKey.review_join_business_action_reject to "Reject",
    MessageKey.review_join_business_feedback_approved to "Join request approved",
    MessageKey.review_join_business_feedback_rejected to "Join request rejected",
    MessageKey.review_business_pending_requests to "Pending requests",
    MessageKey.review_business_select_all to "Select all",
    MessageKey.review_business_description_label to "Description",
    MessageKey.review_business_auto_accept_deliveries to "Auto-accept deliveries",
    MessageKey.review_business_approve_selected to "Approve selected",
    MessageKey.review_business_reject_selected to "Reject selected",
    MessageKey.register_business to "Register business",
    MessageKey.register_business_success to "Request sent",
    MessageKey.business_name to "Business name",
    MessageKey.business_description to "Business description",
    MessageKey.business_admin_email to "Administrator email",
    MessageKey.register_saler_title to "Register seller",
    MessageKey.register_saler_submit to "Register seller",
    MessageKey.register_saler_success to "Registration sent",
    MessageKey.register_saler_email_invalid to "Enter a valid email address",
    MessageKey.signup to "Sign up",
    MessageKey.signup_platform_admin_title to "Platform admin signup",
    MessageKey.signup_platform_admin_submit to "Register platform admin",
    MessageKey.signup_platform_admin to "Platform admin signup",
    MessageKey.signup_delivery to "Delivery signup",
    MessageKey.signup_delivery_title to "Delivery signup",
    MessageKey.signup_delivery_submit to "Register delivery driver",
    MessageKey.text_field_hide_password to "Hide password",
    MessageKey.text_field_show_password to "Show password",
    MessageKey.username to "Username",
    MessageKey.two_factor_verify_submit to "Verify code",
    MessageKey.two_factor_verify_success to "Code verified",
)
