package ar.com.intrale.strings.catalog

import ar.com.intrale.strings.model.MessageKey

internal val DefaultCatalog_en: Map<MessageKey, String> = mapOf(
    MessageKey.app_name to "Intrale",
    MessageKey.buttons_preview_login to "Sign in",
    MessageKey.buttons_preview_logout to "Sign out",
    MessageKey.buttons_preview_signup to "Create account",
    MessageKey.buttons_preview_title to "Buttons preview",
    MessageKey.app_back_button to "Go back",
    MessageKey.app_home_icon_content_description to "Go to home",
    MessageKey.app_missing_title to "Screen without title",
    MessageKey.home_title to "Home",
    MessageKey.home_headline to "We boost your operation with Intrale",
    MessageKey.home_subtitle to "Sign in or sign up to centralize your business and manage your commercial network.",
    MessageKey.confirm_password_recovery to "Confirm recovery",
    MessageKey.error_generic to "Something went wrong. Please try again.",
    MessageKey.family_name to "Last name",
    MessageKey.login_button to "Sign in",
    MessageKey.login_change_password_description to "Your account must update the password before signing in.",
    MessageKey.login_change_password_required to "Update your password to continue",
    MessageKey.login_change_password_title to "Update your password",
    MessageKey.login_email_placeholder to "email@intrale.com",
    MessageKey.login_error_credentials to "Incorrect username or password",
    MessageKey.login_family_name_placeholder to "Last name",
    MessageKey.login_generic_error to "There was an error while signing in. Try again.",
    MessageKey.login_name_placeholder to "First name",
    MessageKey.login_new_password_placeholder to "Secure new password",
    MessageKey.login_password_icon_content_description to "Password icon",
    MessageKey.login_password_placeholder to "Your password",
    MessageKey.login_subtitle to "Sign in with your corporate email to continue.",
    MessageKey.login_title to "Welcome to Intrale",
    MessageKey.login_user_icon_content_description to "User icon",
    MessageKey.first_name to "Name",
    MessageKey.new_password to "New password",
    MessageKey.password to "Password",
    MessageKey.password_recovery to "Recover password",
    MessageKey.register_business to "Register business",
    MessageKey.signup to "Sign up",
    MessageKey.signup_delivery to "Delivery signup",
    MessageKey.text_field_hide_password to "Hide password",
    MessageKey.text_field_show_password to "Show password",
    MessageKey.username to "Username",
)
