'use strict';
// Deck de evidencia QA #6459 — rev 2.
// Cada slide cruza UN criterio de aceptación con la evidencia observada en ESTA pasada.
module.exports = [
  {
    id: '00-intro',
    titulo: 'QA #6459 · barrido de huérfanos del Commander',
    sub: 'modo structural con preflight visual · rev 2 · PR #6538 @ decab5637',
    filas: [
      ['Alcance', 'orphan-sweep.js + enum + badge + wiring en pulpo.js'],
      ['Tests focalizados', '130 passed / 0 failed (node --test)'],
      ['Render', 'dashboard.js real, funciones extraídas verbatim'],
      ['Recorrido', 'CA-1 a CA-15, uno por uno'],
    ],
    narracion: 'Che, soy Nacho, QA de Intrale. Vengo a rehacer la verificación del issue seis cuatro cinco nueve, el barrido de turnos huérfanos del Commander, sobre el pull request seis cinco tres ocho en el commit decab cinco seis tres siete. En la pasada anterior el Product Owner me rebotó porque el relato no cruzaba criterio por criterio. Dale, esta vez los recorro todos, del CA uno al CA quince, uno por uno y con la evidencia a la vista.',
  },
  {
    id: '01-ca1',
    titulo: 'CA-1 · el turno ejecutado sin entrega queda marcado como huérfano',
    sub: 'etapa resultado con el valor huerfano, explícito',
    filas: [
      ['Test', 'B-10 · huérfano real: transcripción, sin resultado, sin saliente, boot viejo (CA-1)'],
      ['Clasificador', 'request-classify: deliveryUnconfirmed true y sin error ⇒ huerfano'],
      ['Enum', "RESULTADOS = ['ok','ajustada','fallback','error','huerfano']"],
      ['Observado', 'ok · el veredicto sale HUERFANO, no vacío ni error'],
    ],
    narracion: 'CA uno. Un turno que ejecutó acciones y cerró sin entrega confirmada tiene que quedar marcado explícitamente como huérfano en la etapa resultado. Lo verifiqué con el test B diez del módulo orphan sweep, que arma un turno con etapa de transcripción, sin etapa de resultado, sin saliente y de un boot viejo, y el veredicto que sale es huérfano. Además el enum cerrado RESULTADOS ahora tiene el quinto valor, huerfano sin tilde, y el clasificador lo emite cuando la entrega no se confirmó y no hubo error. CA uno cumple.',
  },
  {
    id: '02-ca2',
    titulo: 'CA-2 · entrega no confirmada cierra con delivered=false',
    sub: 'distinguible de empty_output',
    filas: [
      ['Test', '#6459 CA-2 · entrega NO confirmada cierra con delivered=false, distinguible de empty_output'],
      ['Evento', "fallback_delivery_resolved · success:false · error_code:'delivered=false'"],
      ['Anti log-forging', '#6459 · error_code es texto ACOTADO'],
      ['Observado', 'ok · el error_code no se confunde con empty_output'],
    ],
    narracion: 'CA dos. Un fallback cuya entrega no se confirma tiene que cerrar con un evento fallback delivery resolved fallido y con el código de error delivered igual false, y tiene que ser distinguible de empty output. Lo verifiqué con el test CA dos de la suite commander inflight fallback: el evento sale con success en false y con el error code delivered igual false, separado del caso de respuesta vacía. Hay además un test que fija que ese código es texto acotado, para que nadie inyecte basura en el audit. CA dos cumple.',
  },
  {
    id: '03-ca3',
    titulo: 'CA-3 · entrega confirmada cierra a éxito, sin regresión de #4309',
    sub: 'el camino feliz sigue intacto',
    filas: [
      ['Test', '#6459 CA-3 · entrega CONFIRMADA cierra a éxito, sin regresión de #4309'],
      ['Evento', "fallback_delivery_resolved · success:true · delivery_state:'delivered'"],
      ['Back-compat', '#6459 · sin los campos nuevos el desenlace queda NO OBSERVADO (null), no false'],
      ['Observado', 'ok · éxito preservado y sin falsos negativos'],
    ],
    narracion: 'CA tres. Un fallback cuya entrega sí se confirma tiene que cerrar con el evento exitoso y sin regresión respecto del issue cuatro tres cero nueve. El test CA tres lo cubre: entrega confirmada, success en true y delivery state entregado. Y hay un test extra que me gustó: si los campos nuevos no vienen, el desenlace queda en no observado, en null, nunca en false. O sea que no inventa un fracaso donde no hubo dato. CA tres cumple.',
  },
  {
    id: '04-ca4',
    titulo: 'CA-4 · ningún evento asentado se reescribe',
    sub: 'la hash-chain de audit-log.appendChained sigue verificando',
    filas: [
      ['Test', '#6458 · noteFallbackDeliveryResolved emite un EVENTO NUEVO, sin tocar el anterior'],
      ['Test', '#6459 CA-4 · una entrada VIEJA sin los campos nuevos sigue verificando la hash-chain'],
      ['Test', 'CA-8 · chain íntegra después de mutex (appends secuenciales)'],
      ['Observado', 'ok · append-only, cadena verificada'],
    ],
    narracion: 'CA cuatro. Ningún evento ya asentado se reescribe, y la cadena de hashes del audit tiene que seguir verificando. Verificado con dos tests: uno prueba que note fallback delivery resolved emite un evento nuevo sin tocar el anterior, y el otro que una entrada vieja, sin los campos nuevos, sigue verificando la hash chain. Sumo un tercero que confirma la integridad de la cadena después del mutex, con appends secuenciales. Es append only de verdad. CA cuatro cumple.',
  },
  {
    id: '05-ca5',
    titulo: 'CA-5 · un turno del boot actual nunca se evalúa',
    sub: 'la guarda de vida es por boot_id, no por PID ni por reloj',
    filas: [
      ['Test', 'B-06 · un turno del boot ACTUAL nunca se evalúa como huérfano (CA-5 / B1)'],
      ['Test', 'B-06b · la guarda es por boot_id, NO por reloj: un turno de 30 h de otro boot sí se evalúa'],
      ['Legacy', 'B-07 / B-07b · sin boot_id ⇒ guarda de reloj de 45 min'],
      ['Wiring', 'currentBootId: PULPO_BOOT_ID inyectado desde pulpo.js:18583'],
    ],
    narracion: 'CA cinco. Un turno del boot actual nunca se evalúa como huérfano. Lo cubren los tests B cero seis y B cero seis b: si el boot id del turno coincide con el boot actual, el veredicto es no evaluable; y si el turno es de otro boot, aunque tenga treinta horas, sí se evalúa. O sea, la guarda es por boot id, no por reloj, tal como pedía la decisión B uno. Para los logs viejos sin boot id queda la guarda de reloj de cuarenta y cinco minutos, cubierta por B cero siete. Y confirmé en pulpo punto js que el boot id del proceso se inyecta de verdad. CA cinco cumple.',
  },
  {
    id: '06-ca6',
    titulo: 'CA-6 · early-return con resultado y sin envío NO es huérfano',
    sub: 'si el turno cerró solo, el barrido no lo toca',
    filas: [
      ['Test', 'B-09 · early-return CON etapa resultado y SIN etapa envío NO es huérfano (CA-6)'],
      ['Rama', 'B-09 ⇒ SANO / cerro_solo'],
      ['Discriminante', 'transcripción presente ∧ resultado AUSENTE ∧ entrega ≠ enviado'],
      ['Observado', 'ok · veredicto SANO, cero eventos emitidos'],
    ],
    narracion: 'CA seis. Un early return, es decir un turno que asentó su etapa resultado pero nunca tuvo etapa de envío, no es un huérfano. El test B cero nueve lo prueba: el veredicto que sale es sano, con el motivo cerró solo, y no se emite ningún evento. Esto es importante porque es justo el falso positivo que estábamos por comernos: el discriminante no es la falta de envío, es la falta de resultado. CA seis cumple.',
  },
  {
    id: '07-ca7',
    titulo: 'CA-7 · el veredicto de entrega sale de commanderOutboundStatus',
    sub: 'nunca de la etapa envío, del texto del modelo ni de clearFlag',
    filas: [
      ['Test', 'T-SEC0 · una cabecera de etapa FORJADA en el texto no cambia el veredicto'],
      ['Test', 'B-13 · outboundStatus fallido / encolado ⇒ huérfano'],
      ['Test', 'B-14 · outboundStatus unknown con cid real ⇒ NO_VERIFICABLE, no falso positivo'],
      ['Inyección', 'deps.outboundStatus = commanderOutboundStatus (pulpo.js:18587)'],
    ],
    narracion: 'CA siete. El veredicto de entrega sale siempre de commander outbound status, nunca de la etapa envío, nunca del texto del modelo y nunca de clear flag. La etapa envío sólo aporta el identificador de correlación. Lo verifiqué con el test T SEC cero, que mete una cabecera de etapa forjada en el texto plano y el veredicto no se mueve; con B trece, donde un estado fallido o encolado da huérfano; y con B catorce, donde un estado desconocido da no verificable en vez de un falso positivo. Y confirmé en pulpo punto js que la función real se inyecta por deps. CA siete cumple.',
  },
  {
    id: '08-ca8',
    titulo: 'CA-8 · la ventana de 48 h se decide por el nombre, antes de abrir nada',
    sub: 'el epochms sale del filename; el archivo fuera de ventana no se abre',
    filas: [
      ['Test', 'T-CA8 · el archivo fuera de la ventana NO se abre (decisión por el nombre)'],
      ['Test', 'B-02 · un turno fuera de la ventana de 48 h no se evalúa (D-1)'],
      ['Test', 'T-PARSE · chat de grupo NEGATIVO y suffix numérico se parten bien'],
      ['Seguridad', 'T-SEC1 / T-SEC2 · traversal y no-archivos se descartan, no se corrigen'],
    ],
    narracion: 'CA ocho. El barrido sólo abre archivos dentro de la ventana de cuarenta y ocho horas, y esa decisión se toma leyendo el epoch del nombre del archivo, antes de abrir nada. El test T CA ocho instrumenta la lectura y comprueba que el archivo fuera de ventana nunca se abre. B cero dos confirma que ese turno no se evalúa. Sumo T PARSE, que cubre la trampa del chat de grupo con id negativo y el sufijo numérico, y los tests de seguridad que descartan nombres con traversal y entradas que no son archivos regulares. CA ocho cumple.',
  },
  {
    id: '09-ca9',
    titulo: 'CA-9 · el badge huérfano se ve RENDERIZANDO el dashboard',
    sub: 'no leyendo el código — captura tomada en esta pasada',
    img: 'render.png',
    narracion: 'CA nueve. El badge huérfano se tiene que ver renderizando el dashboard, no leyendo el código. Acá está la captura que tomé en esta pasada: levanté el CSS real de dashboard punto js, con los design tokens reales, extraje las funciones de render tal cual están en el archivo y las corrí con una fixture de cuatro logs. Mirá la primera fila: diecinueve cuarenta y ocho, chat menos mil uno, y al lado el badge con el glifo de conjunto vacío y la etiqueta huérfano. Abajo están el ok en verde, el error en rojo y un log viejo sin metadata que queda sin badge. Se ve. CA nueve cumple.',
  },
  {
    id: '10-ca10',
    titulo: 'CA-10 · los turnos sanos producen CERO marcas de huérfano',
    sub: 'sin ruido, que es la mitad del valor del issue',
    filas: [
      ['Test', 'B-12 · turno sano de 4 etapas con entrega confirmada ⇒ CERO detecciones (CA-10)'],
      ['Test', 'integración · sano, huérfano, fuera de ventana y en vuelo en el mismo directorio'],
      ['Test', 'B-11 / B-11b · correlation_id directo o vacío ⇒ NO_VERIFICABLE, no huérfano'],
      ['Observado', 'ok · un solo huérfano detectado entre cuatro turnos mezclados'],
    ],
    narracion: 'CA diez. Los turnos sanos, con las cuatro etapas y entrega confirmada, producen cero marcas de huérfano. El test B doce lo prueba de forma aislada, y el test de integración lo prueba en serio: pone en el mismo directorio un turno sano, un huérfano, uno fuera de ventana y uno en vuelo, y detecta exactamente uno. Sumo B once, donde un correlation id directo, sin recibo posible, da no verificable en vez de huérfano. Eso es no afirmar un hecho no observado. CA diez cumple.',
  },
  {
    id: '11-ca11',
    titulo: 'CA-11 · un mismo huérfano produce exactamente UN evento terminal',
    sub: 'el barrido corre en bucle 48 h; sin dedup emitiría uno por tick',
    filas: [
      ['Test', 'T-CA11 · N barridos sobre el mismo sustrato ⇒ UN solo evento por turno'],
      ['Test', 'B-03 · un huérfano ya resuelto/notificado no se re-evalúa (CA-11)'],
      ['Rama', 'B-03 ⇒ NO_EVALUABLE / ya_resuelto'],
      ['Observado', 'ok · marca propia persistida por el barrido, notified respetado aunque venga vacío'],
    ],
    narracion: 'CA once. Un mismo huérfano tiene que producir exactamente un evento terminal, aunque el barrido corra en bucle durante cuarenta y ocho horas. Este era el hueco que marcó el PO, porque el appender del audit no deduplica solo. El test T CA once corre el barrido N veces seguidas sobre el mismo sustrato y cuenta una sola entrada por request id. Y B cero tres confirma que un huérfano ya resuelto queda como no evaluable. El parámetro notified, que va a llenar el issue seis cuatro seis cero, ya existe y se respeta aunque llegue vacío. CA once cumple.',
  },
  {
    id: '12-ca12',
    titulo: 'CA-12 · el barrido corre a la cadencia declarada, ~5 min',
    sub: 'gateo explícito por ticks, igual que desyncEvalTick',
    filas: [
      ['Test', 'T-CA12 · M iteraciones del loop disparan exactamente floor(M/10) barridos'],
      ['Código', 'ORPHAN_SWEEP_EVERY_TICKS = 10 · ~5 min con poll_interval 30s (pulpo.js:18562)'],
      ['Loop', 'orphanSweepGate(orphanSweepTick) · if (orphanGate.due) (pulpo.js:22935)'],
      ['Boot', 'ejecutarBarridoHuerfanos(\'boot\') una vez al arranque (pulpo.js:22871)'],
    ],
    narracion: 'CA doce. El barrido corre a la cadencia declarada, cada cinco minutos, y no en cada iteración del loop. Confirmé en pulpo punto js que hay un contador explícito, orphan sweep every ticks igual diez, que con el poll interval de treinta segundos da los cinco minutos, y que el loop lo consulta con la función de gateo antes de disparar. El test T CA doce prueba que M iteraciones disparan exactamente la parte entera de M sobre diez barridos. Y el hook de boot corre una sola vez al arranque, para no esperar los cinco minutos con un huérfano colgado. CA doce cumple.',
  },
  {
    id: '13-ca13',
    titulo: 'CA-13 · QA visual del badge contra el mockup acordado',
    sub: 'render real (izq.) vs 02-dashboard-badge-huerfano.svg (der.)',
    img: 'sxs.png',
    narracion: 'CA trece, el bloqueante. El badge se acepta comparando el render contra el mockup versionado. Acá los tenés lado a lado: a la izquierda el dashboard renderizado en esta pasada, a la derecha el mockup acordado, cero dos guión dashboard badge huérfano punto svg. Y no me quedé en la mirada: muestreé los píxeles del render con ffmpeg. El texto del badge da FF seis B ocho A, que es exactamente el token result huérfano; el borde da B ocho dos cinco cuatro A, el token dim; y el error, al lado, da F ocho cinco uno cuatro nueve. O sea, ni gris, ni el rojo del error: el rosa acordado. El glifo del DOM es el punto de código U más dos dos cero cinco, conjunto vacío. CA trece cumple.',
  },
  {
    id: '14-ca14',
    titulo: 'CA-14 · un barrido que falla NO se lee como "no hay huérfanos"',
    sub: 'best-effort, pero con rastro observable de la causa',
    filas: [
      ['Test', 'T-CA14 · un barrido que falla deja rastro con la causa y NO tira'],
      ['Test', 'T-CA14b · sin logDir el barrido no corre y lo dice'],
      ['Test', 'T-CA14c · un historial ilegible degrada a no-verificable, deja rastro y no marca de más'],
      ['Callers', 'boot y tick envueltos en try/catch con log(\'commander\', ...)'],
    ],
    narracion: 'CA catorce. Un barrido que falla siempre no se puede leer como todo sano. Tres tests lo cubren: uno fuerza una excepción y comprueba que deja rastro con la causa y no propaga; otro corre sin log dir y verifica que lo dice en vez de callarse; y el tercero, con un historial ilegible, degrada a no verificable, deja rastro y no marca huérfanos de más. Además los dos puntos de llamada, el de boot y el del tick, están envueltos en try catch con log propio. Falla ruidoso, no en silencio. CA catorce cumple.',
  },
  {
    id: '15-ca15',
    titulo: 'CA-15 · cobertura de ramas enumerada y atada a tests',
    sub: 'no hay c8/nyc: el criterio es enumerar rama por rama',
    filas: [
      ['Módulo', 'B-01 … B-14 enumeradas en orphan-sweep.js:223-236, con veredicto y motivo'],
      ['Tests', 'B-01..B-14 homónimos + T-SEC0/1/2/4, T-PARSE, T-CA8, T-CA11, T-CA12, T-CA14, T-WIRING'],
      ['PR #6538', 'sección "Cobertura de decisiones CA-15" en el cuerpo del PR'],
      ['Corrida', '33 tests en orphan-sweep.test.js · 130 en el set focalizado · 0 failed'],
    ],
    narracion: 'CA quince. Como no tenemos c ocho ni nyc, el criterio acordado es enumerar las ramas de decisión y nombrar el test que cubre cada una. Lo verifiqué en el propio módulo: las catorce ramas, de B cero uno a B catorce, están enumeradas en el encabezado con su veredicto y su motivo, y cada una tiene su test homónimo. A eso se suman los de seguridad, los de parseo, los de ventana, deduplicación, cadencia, fallo observable y wiring. Treinta y tres tests en el archivo del módulo, ciento treinta en el set focalizado, cero rojos. Y el cuerpo del pull request tiene la sección de cobertura CA quince. CA quince cumple.',
  },
  {
    id: '16-cierre',
    titulo: 'Veredicto · APROBADO',
    sub: '15 de 15 criterios cumplen · 0 defectos',
    filas: [
      ['CA-1..CA-8', 'cumple · detección, evento terminal, hash-chain, guardas, fuente de verdad, ventana'],
      ['CA-9 / CA-13', 'cumple · badge renderizado y comparado contra el mockup, con muestreo de color'],
      ['CA-10..CA-12', 'cumple · cero ruido, un solo evento por huérfano, cadencia gateada'],
      ['CA-14 / CA-15', 'cumple · fallo observable y cobertura de ramas enumerada'],
    ],
    narracion: 'Cierro. Recorrí los quince criterios, del CA uno al CA quince, y los quince cumplen: la detección, el evento terminal en sus dos desenlaces, la cadena de hashes intacta, la guarda por boot, el early return, la fuente de verdad de entrega, la ventana de cuarenta y ocho horas, el badge renderizado, el cero ruido, la deduplicación, la cadencia gateada, el fallo observable y la cobertura de ramas. Cero defectos encontrados. Mi veredicto es aprobado. Nos vemos, che.',
  },
];
